//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_kafedra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson_schedule
    {
        public int LessonID { get; set; }
        public int DisciplineID { get; set; }
        public int GroupID { get; set; }
        public int TeacherID { get; set; }
        public string Time_lesson { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
