//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_kafedra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teachers()
        {
            this.Lesson_schedule = new HashSet<Lesson_schedule>();
            this.Statement = new HashSet<Statement>();
        }
    
        public int TeacherID { get; set; }
        public Nullable<int> KafedraID { get; set; }
        public string Teacher_surname { get; set; }
        public string Teacher_name { get; set; }
        public string Teacher_patronymic { get; set; }
        public string Position { get; set; }
        public string AcademicRank { get; set; }
        public Nullable<decimal> EmploymentRate { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
    
        public virtual Kafedra Kafedra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson_schedule> Lesson_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statement> Statement { get; set; }
    }
}
